spring:
  profiles:
    active: test

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      url: jdc:h2:mem:testdb
      username: sa
      password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
