# Generated by Django 4.2.3 on 2023-08-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
    ]
